### ISSUE TITLE
OKXのsizeの扱い

### ISSUE THREAD

**Issue by yota-p** [ko0hi/pybotters-wrapper#129]
OKXTradesStore, OrderBookStoreのsizeが妙に大きいので調査していたところ、OKXのsizeの扱いについて少し考慮が必要そうなので一旦共有させていただきます。

https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/okx/store.py#L28
https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/okx/store.py#L39

https://www.okx.com/docs-v5/en/#websocket-api-public-channel-trades-channel
https://www.okx.com/docs-v5/en/#websocket-api-public-channel-order-book-channel

OKXのWebsocketで流れてくる`sz`項目について、spotは数量が入って来るんですが、derivatives（perp, future, option）はコントラクト数（数量ではない）が流れてくる仕様のようです。[APIドキュメント](https://www.okx.com/docs-v5/en/#rest-api-trade-place-order)にこんな記載がありました。

> sz
Quantity to buy or sell.
For SPOT/MARGIN Buy and Sell Limit Orders, it refers to the quantity in base currency.
For SPOT/MARGIN Buy Market Orders, it refers to the quantity in quote currency.
For SPOT/MARGIN Sell Market Orders, it refers to the quantity in base currency.
**For FUTURES/SWAP/OPTION orders, it refers to the number of contracts.**

例えばBTCUSDT無期限: BTC-USDT-SWAPの[Contract size](https://www.okx.com/trade-market/info/swap)は0.01 BTCなので、0.01BTCの約定があるとWebsocketには`"sz": "1"`が流れてきます。

一方、現状bitflyerやbinanceのsizeはコントラクト数量がセットされているので、okxだけsizeに持っている値の意味が違っている状況です。（まだ見れていないですが、orderを出すときのsizeもこのあたりの考慮が必要？）

利用者的にはsizeはコントラクト数量に統一されていた方が使いやすいのですが、どういう方針がいいか相談したいなーと思いました。

1. sizeにコントラクト数量をセットするよう改修する（コントラクトサイズを事前に知っておく必要あり）
2. このままOKXのsizeはコントラクト数のままとする

**Comment by ko0hi** [comment]
起票ありがとうございます！OKXは一部contract sizeでしたか。
自分が認識している範囲だと、`binancecoinm`・`kucoinfutures`もコントラクトサイズで、両者とも**注文もコントラクトサイズで**行う必要があります（`binancecoinm`はアプリだと枚数注文できるんですが、REST経由でコントラクトサイズか枚数サイズか指定するパラメーターが見当たらなかった）。

わかりやすさ的には枚数に統一するだとは思うんですが、結局注文のところでコントラクトサイズに直さないといけないならば余計な手間が増えるだけかな、というのが自分の所感ですね。やるとすれば、変換pluginを作るという方針の方が取り回しが効きやすそうです。

ccxtだとどういう風に扱ってるんですかね

**Comment by yota-p** [comment]
返信遅くなりすみません。他にも同様の取引所があるのですね！
コードを見る限りccxtもコントラクトサイズで注文していました。
https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/okx.py#L2052

ひとまずpluginなり呼び出し元なりで変換するようにします。確認ありがとうございました。
