### ISSUE TITLE
取引所固有のpluginが呼び出せない問題

### ISSUE THREAD

**Issue by MasanoriYamada** [ko0hi/pybotters-wrapper#56]
## 状況

取引所固有のpluginは[ここ](https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/plugins/_apis.py#L24)で
```
pybotters_wrapper.{store.exchange}.plugins
```
のパスを探索しているようにみえます。

一方、store.exchangeは[ここ](https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/utils/mixins.py#L82)で定義されていて
例えばbinanceであれば
```
binancespot
binanceusdsm
binanceusdsm_test
binancecoinm
binancecoinm_test
```
となる用に見えます。
一方pluginがあるディレクトリは
```
binance
```
となっていて、pluginの探索パスに引っかからない。
理解が間違ってたらすいません。

参考までに思いついた対策を一応書きます。

### 対策
[ここ](https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/plugins/_apis.py#L24)に
```
EXCHANGE_TO_PLUGINPATH = {
    "binanceusdsm_test": "binance",
    "binancecoinm_test": "binance",
    "binanceusdsm": "binance",
    "binancecoinm": "binance",
    "binancespot": "binance",
    "bitflyer": "bitflyer",
    "okx": "okx",
    "bybitinverse": "bybit",
    "bybitusdt": "bybit",
    "gmocoin": "gmocoin",
    "bitbank": "bitbank",
    "coincheck": "coincheck",
    "kucoinspot": "kucoin",
    "kucoinfutures": "kucoin",
    "bitget": "bitget",
    "phemex": "phemex"
}


module_path = f"pybotters_wrapper.{EXCHANGE_TO_PLUGINPATH[store.exchange]}.plugins"
```
的な辞書を持たせる。
自分の環境ではこれで動作しました。

**Comment by ko0hi** [comment]
起票ありがとうございます。ご指摘の通りこちらは探索パスの設定ミスです。

現状自分の認識としては以下の通りです。

- パッケージは取引所単位で分けているものの、多くの実装は”サブ”取引所（いい呼称が思いつかない）単位で異なっている
- プラグイン以外にも特定の”サブ”取引所に依存する実装が出てくる気がする
- 例えば、spot系（`binancespot`・`kucoinspot`）のストアにアカウントストアを実装するなど

なので、個人的には"サブ"取引所用のpropertyを与えておいた方が汎用性が高くて良いかなと感じています（編集されましたかね？メール通知にはその対策が書いてあったのを拝見しました）。

名前に関してですが、実際の取引的にもAPI的にも実装的にも"サブ"取引所が実質取引所といった具合になりますよね。
なので、”サブ”取引所に対して名前を用意するよりも、exchange propertyで "サブ"取引所名（`binancespot`）を返して、`package` propertyを追加してそこでパッケージ名（ `binance`）を返すような変更もありかな、と思っています。

どうでしょうか。

**Comment by MasanoriYamada** [comment]
> なので、個人的には"サブ"取引所用のpropertyを与えておいた方が汎用性が高くて良いかなと感じています

同意です。 (編集しました😅 #55 の変更で辞書用意する方向でやっちゃったもので)

> exchange propertyで "サブ"取引所名（binancespot）を返して、package propertyを追加してそこでパッケージ名（ binance）を返すような変更もありかな、と思っています。

いいと思います。
plugin探索のパスは [取引所共通部分](https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/plugins/_apis.py#L24) に書いてありますが、ここの探索はどうしましょう

```
pybotters_wrapper.{store.exchange}.plugins_{store.package}
```
みたいな感じですかね？

**Comment by ko0hi** [comment]
ありがとうございます。
自分寝ぼけていたようで、すでにexchange propertyが返すものはすでに”サブ”取引所名になっていますね。なので変更としては、`package` propertyを`ExchangeMixin`に追加して、そこで対応package名を返すようにしたいと思います。

取引所別プラグインの定義箇所ですが以下のようだとどうでしょうか：

```
.
└── pybotters-wrapper
    └── binance
        └── plugins
            ├── binancecoinm
            │   └── __init__.py
            ├── binancecoinm_test
            │   └── __init__.py
            ├── binancespot
            │   └── __init__.py
            ├── binanceusdsm
            │   ├── __init__.py
            │   └── close_watcher.py
            └── binanceusdsm_test
                └── __init__.py
```

プラグインの定義は __init__.pyでexposeして、importモジュール部分は`pybotters_wrapper.{store.package}.plugins.{store.exchange}`になると思います。

**Comment by ko0hi** [comment]
@MasanoriYamada 

`pybotters_wrapper.pluins._apis._maybe_override_by_exchange`は、「ほとんどの取引所は同じ実装でカバーできるが、一部の取引所でのみオーバーライドが必要な場合」に使う想定でした。具体的には、本家の実装クラスは`pybotters_wrapper.plugins`にあって、オーバーライドしたい場合は同名のクラスを取引所パッケージの中に配置する、という仕様です。

これは元々 #57 で作っていただいたような、完全に特定の取引所に依存したプラグインを想定していなかった点にあります。そのためこちらのファクトリーメソッドを無理に使うのは合わないように感じました。

それで提案なんですが、特定の取引所依存のプラグインに関しては、`pybotters_wrapper.plugins`のファクトリーメソッドを経由させずに、①直接クラスをインスタンス化させる or ②取引所パッケージ内にファクトリーメソッドを用意するというのはいかがでしょうか。

イメージとしてはこんな感じです：

```python
# ①
from pybotters_wrapper.binance.plugins.binanceusdsm import CloseWatcher
watcher = CloseWatcher(...)

# ②
import pybotters_wrapper as pbw
pbw.binance.plugins.binanceusdsm.create_close_watcher(...)
```

個人的には以下の理由で①でいいのかな、と思っています：

- 取引所ごとに_apis.pyを用意してファクトリーメソッドを書いてexposeするのが少々面倒
    - ①であれば、`close_watcher.py`に定義を書いて、`pybotters_wrapper/binance/plugins/binanceusdsm/__init__.py`でexposeして終了
- 一応、全取引所対応と特定取引所依存で生成の仕方に区別がつく


いかがでしょうか。ちなみにもし２の方が好みというのであれば、それでも全然大丈夫です。

**Comment by MasanoriYamada** [comment]
①に賛成です。
シンプルで作る側も書く量が減って、開発に参加しやすいと思いました！

**Comment by ko0hi** [comment]
#64にて定義部分を修正しました。こちらのissueは一旦クローズします。
