### ISSUE TITLE
plugin close watcher

### ISSUE THREAD

**Issue by MasanoriYamada** [ko0hi/pybotters-wrapper#57]
pluginのexecution_watcherにcancelも監視できるようにしたclose watcherの実装をやってみました。

## 使い方

```python
close_watcher = pbw.plugins.close_watcher(store)
resp_order = await api.limit_order(args.symbol, side, price, size)  # 適当な注文
close_watcher.set(resp_order.order_id)  # 監視対象を登録

while not close_watcher.done():
    await asyncio.sleep(1)
    print(close_watcher.status)
print(close_watcher.result())
```

open orderが約定かcancelされたら `close_watcher.done()`がTrueになる。
close_watcher.statusはOPEN, FILLED, CANCELの３種類

使いみちとしては、OCO注文などを作れる。

## 実装に関して
store.orderでのdeleteを監視するだけでは、cancelとfilledの区別がつかないため
infoの中の情報を参照しているため取引所ごとに実装する必要があるという認識。
現在は、binanceのみ実装

またfilledの情報を取るためpybotters==0.15.0の
[watch メソッドの変更クラスに影響されたストアとデータを追加する](https://github.com/MtkN1/pybotters/pull/212)
に対応。

#56 に対応

plugin以外の変更も含まれているため、PRしていいか少し悩んでいます。
もしPRする場合は、sample/misc以下にpluginの使用例を作ったりしたほうがいいですか？

**Comment by ko0hi** [comment]
@MasanoriYamada お待たせしました。現状のmainブランチがpybotters bump up済みで #56 の問題を解決した状態になってます！

ここをベースにPRいただけますと助かります。また、pybottersのbump upによってpluginのsignatureに変更が入っているのでお気をつけください。

**Comment by MasanoriYamada** [comment]
さすが早い！　了解です！

**Comment by ko0hi** [comment]
merged by #66
