### ISSUE TITLE
sourceに含まれるメッセージがpluginの_on_watchまで届いていない

### ISSUE THREAD

**Issue by MasanoriYamada** [ko0hi/pybotters-wrapper#65]
sourceに含まれるメッセージがpluginの_on_watchまで届いていない用に見えます。

[watch メソッドの変更クラスに影響されたストアとデータを追加する](https://github.com/MtkN1/pybotters/pull/212) #52
に対応したchange.sourceを正しく伝搬させるためには
[ここ](https://github.com/ko0hi/pybotters-wrapper/blob/main/pybotters_wrapper/core/store.py#L493)で
```
        return {**transformed_item, "info": {'data': change.data, 'source': change.source}}
```
としないと、item化されるときに change.sourceの情報が消えてしまう気がします。

**Comment by ko0hi** [comment]
close by #67
